# Generated by Django 4.1 on 2023-12-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('phone_number', models.CharField(default=None, max_length=11, null=True)),
                ('grade', models.IntegerField(blank=True, choices=[(1, 'اول'), (2, 'دوم'), (3, 'سوم'), (4, 'چهارم'), (5, 'پنجم'), (6, 'ششم'), (7, 'هفتم'), (8, 'هشتم'), (9, 'نهم'), (10, 'دهم'), (11, 'یازدهم'), (12, 'دوازدهم'), (18, 'فارغ التحصیل')], default=None, null=True)),
                ('major', models.CharField(blank=True, choices=[('ریاضی', 'Math'), ('تجربی', 'Sience'), ('انسانی', 'Humn'), ('هنر', 'Art'), ('سایر', 'Other')], default=None, max_length=20, null=True)),
            ],
        ),
    ]
