# Generated by Django 4.1 on 2023-12-17 15:59

from django.db import migrations, models
import mandapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mandapp', '0003_rename_tel_last_name_user_tel_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, default=None, null=True)),
                ('btn_text', models.TextField(blank=True, default=None, null=True)),
                ('msg_type', models.TextField(blank=True, default=None, null=True)),
                ('msg_id', models.IntegerField(blank=True, default=None, null=True)),
                ('creation_datetime', models.DateTimeField(default=mandapp.models.get_current_datetime)),
                ('finalized', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VrifCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=mandapp.models.get_default_verifCode)),
                ('phone_number', models.CharField(default=None, max_length=11, null=True)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='register_date',
            field=models.DateField(default=mandapp.models.get_current_date),
        ),
    ]
